/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Login */
        post: operations["api_login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Logout */
        post: operations["api_logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Me */
        get: operations["api_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Home */
        get: operations["api_home_api_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shelf/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Shelf */
        get: operations["api_shelf_api_shelf__status__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shelf/wanted/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Reorder Wanted Shelf */
        post: operations["api_reorder_wanted_shelf_api_shelf_wanted_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Onboarding */
        post: operations["api_onboarding_api_onboarding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Book Detail */
        get: operations["api_book_detail_api_book__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Stats */
        get: operations["api_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Calendar */
        get: operations["api_calendar_api_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Settings */
        get: operations["api_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Settings Goal */
        post: operations["api_settings_goal_api_settings_goal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Settings Sync */
        post: operations["api_settings_sync_api_settings_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/shelves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Settings Shelves */
        get: operations["api_settings_shelves_api_settings_shelves_get"];
        put?: never;
        /** Api Settings Shelves Update */
        post: operations["api_settings_shelves_update_api_settings_shelves_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/spice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Settings Spice */
        post: operations["api_settings_spice_api_settings_spice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Search Library */
        get: operations["api_search_library_api_search_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Search */
        get: operations["api_search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/more": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Search More */
        get: operations["api_search_more_api_search_more_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tbr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Add To Tbr */
        post: operations["api_add_to_tbr_api_tbr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tbr/{entry_id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Remove From Tbr */
        post: operations["api_remove_from_tbr_api_tbr__entry_id__remove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tbr/{entry_id}/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Set Tbr Dates */
        post: operations["api_set_tbr_dates_api_tbr__entry_id__dates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Set View Preference */
        post: operations["api_set_view_preference_api_preferences_view_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences/calendar-view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Set Calendar View Preference */
        post: operations["api_set_calendar_view_preference_api_preferences_calendar_view_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Admin */
        get: operations["api_admin_api_admin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/library-sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Admin Library Sync */
        post: operations["api_admin_library_sync_api_admin_library_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/library-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Admin Library Search */
        get: operations["api_admin_library_search_api_admin_library_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/books/{book_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Admin Match Book */
        post: operations["api_admin_match_book_api_admin_books__book_id__match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audiobooks/{audiobook_grimmory_id}/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Admin Pair Audiobook */
        post: operations["api_admin_pair_audiobook_api_admin_audiobooks__audiobook_grimmory_id__pair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Admin Settings */
        get: operations["api_admin_settings_api_admin_settings_get"];
        put?: never;
        /** Api Admin Settings Save */
        post: operations["api_admin_settings_save_api_admin_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/hardcover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Admin Settings Save Hardcover */
        post: operations["api_admin_settings_save_hardcover_api_admin_settings_hardcover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/grimmory-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Admin Settings Save Grimmory Admin */
        post: operations["api_admin_settings_save_grimmory_admin_api_admin_settings_grimmory_admin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminEntryOut */
        AdminEntryOut: {
            /** Id */
            id?: number | null;
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            /** Wanted By */
            wanted_by: string[];
            /** Grimmory Id */
            grimmory_id?: number | null;
            /**
             * Manually Matched
             * @default false
             */
            manually_matched: boolean;
            /** Paired Ebook Title */
            paired_ebook_title?: string | null;
        };
        /** AdminMatchIn */
        AdminMatchIn: {
            /** Grimmory Id */
            grimmory_id?: number | null;
        };
        /** AdminOut */
        AdminOut: {
            /** Needed Entries */
            needed_entries: components["schemas"]["AdminEntryOut"][];
            /** Owned Entries */
            owned_entries: components["schemas"]["AdminEntryOut"][];
            /** Audiobook Entries */
            audiobook_entries: components["schemas"]["AdminEntryOut"][];
            /** Library Check Enabled */
            library_check_enabled: boolean;
            /** Last Synced At */
            last_synced_at?: string | null;
            /** Last Error */
            last_error?: string | null;
        };
        /** AdminPairAudiobookIn */
        AdminPairAudiobookIn: {
            /** Ebook Grimmory Id */
            ebook_grimmory_id?: number | null;
        };
        /** AdminSettingsOut */
        AdminSettingsOut: {
            library_settings?: components["schemas"]["LibrarySettingsOut"] | null;
            grimmory_admin_settings?: components["schemas"]["GrimmoryAdminSettingsOut"] | null;
            /** Hardcover Api Key Set */
            hardcover_api_key_set: boolean;
            /** Default Sync Interval Minutes */
            default_sync_interval_minutes: number;
        };
        /** BookDetailOut */
        BookDetailOut: {
            entry: components["schemas"]["TBREntryOut"];
            /** Tiles */
            tiles: components["schemas"]["StatTileOut"][];
            /** Burndown */
            burndown: components["schemas"]["BurndownPointOut"][];
            /** Burndown Day Span */
            burndown_day_span: number;
            /** Progress Percent */
            progress_percent?: number | null;
            /** Estimated Page */
            estimated_page?: number | null;
            /**
             * Audiobook Tiles
             * @default []
             */
            audiobook_tiles: components["schemas"]["StatTileOut"][];
            /**
             * Audiobook Burndown
             * @default []
             */
            audiobook_burndown: components["schemas"]["BurndownPointOut"][];
            /**
             * Audiobook Burndown Day Span
             * @default 0
             */
            audiobook_burndown_day_span: number;
            /** Audiobook Progress Percent */
            audiobook_progress_percent?: number | null;
            /** Audiobook Estimated Page */
            audiobook_estimated_page?: number | null;
        };
        /** BookOut */
        BookOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /** Isbn */
            isbn?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            /** Published Date */
            published_date?: string | null;
            /** Page Count */
            page_count?: number | null;
            /** Cover Color */
            cover_color?: string | null;
        };
        /**
         * BookSpanOut
         * @description One book's active date range within the requested month — the calendar's unit of data.
         *     DayCellOut entries below reference these by entry_id rather than embedding a copy per day, so
         *     the frontend builds one lookup map instead of re-parsing a book's details on every cell it
         *     appears in.
         */
        BookSpanOut: {
            /** Entry Id */
            entry_id: number;
            book: components["schemas"]["CalendarBookOut"];
            /** Status */
            status: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Lane */
            lane: number;
        };
        /** BurndownPointOut */
        BurndownPointOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Remaining Percent */
            remaining_percent: number;
        };
        /** CalendarBookOut */
        CalendarBookOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Cover Url */
            cover_url?: string | null;
            /** Cover Color */
            cover_color?: string | null;
        };
        /** CalendarOut */
        CalendarOut: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Month Label */
            month_label: string;
            /** Prev Month */
            prev_month: string;
            /** Next Month */
            next_month: string;
            /** Calendar View */
            calendar_view: string;
            /** Spans */
            spans: components["schemas"]["BookSpanOut"][];
            /** Grid */
            grid: components["schemas"]["DayCellOut"][][];
            /** Tiles */
            tiles: components["schemas"]["StatTileOut"][];
        };
        /** CalendarViewPreferenceIn */
        CalendarViewPreferenceIn: {
            /** View */
            view: string;
        };
        /**
         * DayCellOut
         * @description active/cover/bar mirror reading_calendar.DayCell's active_spans/cover_spans/bar_spans —
         *     same precedence (declutter, milestone ranking, lane-gap None-padding) already computed
         *     server-side, just referencing spans by entry_id instead of embedding BookSpan objects.
         *     bar_entry_ids preserves interior None gaps (an unoccupied lane below a higher occupied one);
         *     it is never trimmed to a shorter list than the highest occupied lane + 1.
         */
        DayCellOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** In Month */
            in_month: boolean;
            /** Is Today */
            is_today: boolean;
            /** Is Future */
            is_future: boolean;
            /** Active Entry Ids */
            active_entry_ids: number[];
            /** Cover Entry Ids */
            cover_entry_ids: number[];
            /** Bar Entry Ids */
            bar_entry_ids: (number | null)[];
        };
        /** GoalIn */
        GoalIn: {
            /** Target Count */
            target_count: number;
        };
        /** GoalOut */
        GoalOut: {
            /** Id */
            id: number;
            /** Timeframe */
            timeframe: string;
            /** Target Count */
            target_count: number;
        };
        /** GrimmoryAdminSettingsIn */
        GrimmoryAdminSettingsIn: {
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Password
             * @default
             */
            password: string;
        };
        /** GrimmoryAdminSettingsOut */
        GrimmoryAdminSettingsOut: {
            /** Username */
            username?: string | null;
            /** Password Set */
            password_set: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardcoverSettingsIn */
        HardcoverSettingsIn: {
            /**
             * Hardcover Api Key
             * @default
             */
            hardcover_api_key: string;
        };
        /** HomeOut */
        HomeOut: {
            /** Shelves */
            shelves: components["schemas"]["ShelfOut"][];
        };
        /** LibrarySettingsIn */
        LibrarySettingsIn: {
            /**
             * Base Url
             * @default
             */
            base_url: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Password
             * @default
             */
            password: string;
            /**
             * Sync Interval Minutes
             * @default 60
             */
            sync_interval_minutes: number;
        };
        /** LibrarySettingsOut */
        LibrarySettingsOut: {
            /** Base Url */
            base_url?: string | null;
            /** Username */
            username?: string | null;
            /** Password Set */
            password_set: boolean;
            /** Sync Interval Minutes */
            sync_interval_minutes: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MeOut */
        MeOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** View Preference */
            view_preference: string;
            /** Calendar View Preference */
            calendar_view_preference: string;
            /** Onboarded */
            onboarded: boolean;
            /** Spice Level */
            spice_level: number;
            /** Is Admin */
            is_admin: boolean;
        };
        /** OnboardingIn */
        OnboardingIn: {
            /** Target Count */
            target_count?: number | null;
        };
        /**
         * ReorderIn
         * @description Entry ids for the "wanted" shelf in the desired order (first = top of the shelf) — see
         *     models.py:set_wanted_order, which scopes the update to the caller's own wanted entries only.
         */
        ReorderIn: {
            /** Entry Ids */
            entry_ids: number[];
        };
        /** SearchOut */
        SearchOut: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchResultOut"][];
            /**
             * Error
             * @default false
             */
            error: boolean;
            /** Error Message */
            error_message?: string | null;
            /**
             * Show More
             * @default false
             */
            show_more: boolean;
        };
        /** SearchResultOut */
        SearchResultOut: {
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /** Isbn */
            isbn?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            /** Published Date */
            published_date?: string | null;
            /** Grimmory Id */
            grimmory_id?: number | null;
        };
        /** SettingsOut */
        SettingsOut: {
            goal?: components["schemas"]["GoalOut"] | null;
            /** Goal Year */
            goal_year: number;
            /** Grimmory Admin Configured */
            grimmory_admin_configured: boolean;
            /** Spice Labels */
            spice_labels: string[];
            /** Spice Level */
            spice_level: number;
            /** Has Grimmory Session */
            has_grimmory_session: boolean;
            /** Want To Read Shelf Id */
            want_to_read_shelf_id?: number | null;
            /**
             * Sync To Device Enabled
             * @default false
             */
            sync_to_device_enabled: boolean;
            /** Sync To Device Shelf Id */
            sync_to_device_shelf_id?: number | null;
        };
        /** ShelfOptionOut */
        ShelfOptionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** ShelfOptionsOut */
        ShelfOptionsOut: {
            /** Shelves */
            shelves: components["schemas"]["ShelfOptionOut"][];
            /** Error */
            error?: string | null;
        };
        /** ShelfOut */
        ShelfOut: {
            /** Status */
            status: string;
            /** Label */
            label: string;
            /** Entries */
            entries: components["schemas"]["TBREntryOut"][];
        };
        /** ShelfSyncSettingsIn */
        ShelfSyncSettingsIn: {
            /** Want To Read Shelf Id */
            want_to_read_shelf_id?: number | null;
            /**
             * Sync To Device Enabled
             * @default false
             */
            sync_to_device_enabled: boolean;
            /** Sync To Device Shelf Id */
            sync_to_device_shelf_id?: number | null;
        };
        /** ShelfSyncSettingsOut */
        ShelfSyncSettingsOut: {
            /** Want To Read Shelf Id */
            want_to_read_shelf_id?: number | null;
            /**
             * Sync To Device Enabled
             * @default false
             */
            sync_to_device_enabled: boolean;
            /** Sync To Device Shelf Id */
            sync_to_device_shelf_id?: number | null;
        };
        /** SpiceIn */
        SpiceIn: {
            /** Level */
            level: number;
        };
        /** SpiceResultOut */
        SpiceResultOut: {
            /** Spice Level */
            spice_level: number;
            /** Error */
            error?: string | null;
        };
        /** StatTileOut */
        StatTileOut: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Sub */
            sub?: string | null;
        };
        /** StatsOut */
        StatsOut: {
            /** Year */
            year: number;
            goal?: components["schemas"]["GoalOut"] | null;
            /** Finished Count */
            finished_count: number;
            /** Tiles */
            tiles: components["schemas"]["StatTileOut"][];
        };
        /** SyncIn */
        SyncIn: {
            /**
             * Password
             * @default
             */
            password: string;
        };
        /** SyncResultOut */
        SyncResultOut: {
            /** Error */
            error?: string | null;
        };
        /** TBRCreateIn */
        TBRCreateIn: {
            /** Title */
            title: string;
            /**
             * Author
             * @default
             */
            author: string;
            /**
             * Isbn
             * @default
             */
            isbn: string;
            /**
             * Cover Url
             * @default
             */
            cover_url: string;
            /**
             * Published Date
             * @default
             */
            published_date: string;
            /**
             * Grimmory Id
             * @default
             */
            grimmory_id: string;
        };
        /** TBRDatesIn */
        TBRDatesIn: {
            /**
             * Started At
             * @default
             */
            started_at: string;
            /**
             * Finished At
             * @default
             */
            finished_at: string;
        };
        /** TBREntryOut */
        TBREntryOut: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Added At */
            added_at: string;
            book: components["schemas"]["BookOut"];
            /** Owned */
            owned?: boolean | null;
            /** Has Paired Audiobook */
            has_paired_audiobook?: boolean | null;
            /** Finished At */
            finished_at?: string | null;
            /** Started At */
            started_at?: string | null;
            /**
             * Started At Manual
             * @default false
             */
            started_at_manual: boolean;
            /** Rating */
            rating?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ViewPreferenceIn */
        ViewPreferenceIn: {
            /** View */
            view: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"] | null;
                };
            };
        };
    };
    api_home_api_home_get: {
        parameters: {
            query?: {
                today?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_shelf_api_shelf__status__get: {
        parameters: {
            query?: {
                today?: string;
            };
            header?: never;
            path: {
                status: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_reorder_wanted_shelf_api_shelf_wanted_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_onboarding_api_onboarding_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_book_detail_api_book__entry_id__get: {
        parameters: {
            query?: {
                today?: string;
            };
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_stats_api_stats_get: {
        parameters: {
            query?: {
                today?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_calendar_api_calendar_get: {
        parameters: {
            query?: {
                month?: string;
                today?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_settings_api_settings_get: {
        parameters: {
            query?: {
                today?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_settings_goal_api_settings_goal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_settings_sync_api_settings_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_settings_shelves_api_settings_shelves_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfOptionsOut"];
                };
            };
        };
    };
    api_settings_shelves_update_api_settings_shelves_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShelfSyncSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfSyncSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_settings_spice_api_settings_spice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpiceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpiceResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_search_library_api_search_library_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_search_api_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_search_more_api_search_more_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_add_to_tbr_api_tbr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TBRCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TBREntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_remove_from_tbr_api_tbr__entry_id__remove_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_set_tbr_dates_api_tbr__entry_id__dates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TBRDatesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TBREntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_set_view_preference_api_preferences_view_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewPreferenceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_set_calendar_view_preference_api_preferences_calendar_view_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarViewPreferenceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_admin_api_admin_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOut"];
                };
            };
        };
    };
    api_admin_library_sync_api_admin_library_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_admin_library_search_api_admin_library_search_get: {
        parameters: {
            query?: {
                q?: string;
                exclude_audiobooks?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_admin_match_book_api_admin_books__book_id__match_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminMatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_admin_pair_audiobook_api_admin_audiobooks__audiobook_grimmory_id__pair_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audiobook_grimmory_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPairAudiobookIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_admin_settings_api_admin_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettingsOut"];
                };
            };
        };
    };
    api_admin_settings_save_api_admin_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibrarySettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_admin_settings_save_hardcover_api_admin_settings_hardcover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HardcoverSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_admin_settings_save_grimmory_admin_api_admin_settings_grimmory_admin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrimmoryAdminSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
